#!/bin/bash
set -e

mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
    -- Tworzenie baz danych
    CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE_AUTH}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE_FINANCE}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    -- Tworzenie użytkownika AUTH
    CREATE USER IF NOT EXISTS '${MYSQL_USER_AUTH}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD_AUTH}';
    GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE_AUTH}\`.* TO '${MYSQL_USER_AUTH}'@'%';

    -- Tworzenie użytkownika FINANCE
    CREATE USER IF NOT EXISTS '${MYSQL_USER_FINANCE}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD_FINANCE}';
    GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE_FINANCE}\`.* TO '${MYSQL_USER_FINANCE}'@'%';

    FLUSH PRIVILEGES;
EOSQL
